[@no_mutation] let only_signer = "Only one of the contract signer can create an proposal"
[@no_mutation] let amount_must_be_zero_tez = "You must not send Tezos to the smart contract"
[@no_mutation] let no_proposal_exist = "No proposal exists for this counter"
[@no_mutation] let has_already_signed = "You have already signed this proposal"
[@no_mutation] let unknown_contract_entrypoint = "Cannot connect to the target transfer token entrypoint"